import { AppDispatch } from '../../../store';
import { addAkihabaraGrid } from './AkihabaraGrid';
import { addGinzaGrid } from './GinzaGrid';
import { addKandaGrid } from './KandaGrid';
import { addKitaSenjuGrid } from './KitaSenjuGrid';
import { addKyobashiGrid } from './KyobashiGrid';
import { addNipporiGrid } from './NipporiGrid';
import { addOedoGrid } from './OedoGrid';
import { addOedoSouthGrid } from './OedoSouthGrid';
import { addShimbashiGrid } from './ShimbashiGrid';
import { addShinjukuGrid } from './ShinjukuGrid';
import { addTabataGrid } from './TabataGrid';
import { addTokyo } from './TokyoGrid';
import { addTozaiGrid } from './TozaiGrid';
import { addUenoGrid } from './UenoGrid';
import { addYotsuyaGrid } from './YotsuyaGrid';
import { addYurakuchoGrid } from './YurakuchoGrid';

export const addCentralGrid = (dispatch: AppDispatch) => {
    dispatch(addTokyo);
    dispatch(addTozaiGrid);
    dispatch(addKyobashiGrid);
    dispatch(addKandaGrid);
    dispatch(addYurakuchoGrid);
    dispatch(addGinzaGrid);
    dispatch(addShimbashiGrid);
    dispatch(addAkihabaraGrid);
    dispatch(addOedoGrid);
    dispatch(addUenoGrid);
    dispatch(addNipporiGrid);
    dispatch(addKitaSenjuGrid);
    dispatch(addTabataGrid);
    dispatch(addYotsuyaGrid);
    dispatch(addShinjukuGrid);
    dispatch(addOedoSouthGrid);
};
